### ISSUE TITLE
[주특기 숙련주차 과제 리뷰]

### ISSUE THREAD

**Issue by lilclown97** [lilclown97/TIL#3]
GitHub,API명세서 : https://github.com/lilclown97/TIL/tree/main/%ED%95%AD%ED%95%B499/W4-SPA_POST-login
과제 : http://sparta-lilclown.shop/

1. `router.get('/posts/:postsId/:commentsId'...` 이런식으로 params 값을 두개씩 가져오기도 하는지, 그렇다면 어떤 경우에 보통 사용 하는지.

2. `/routes` 안의 API들이 RESTful 한지, 그렇지 않다면 과제로 구현한 API 를 어떻게 더 RESTful 하게 바꿀 수 있는지 예시 등

3. 아래의 코드에서 '로그인 중' 을 표현하기 위해 Thunder client - Headers 부분에 `token` 이라는 항목을 추가해 그것을 검사하는 방식으로 토큰이 있으면 '로그인 중' 아니라면 로그인을 할 수 있게끔 구현했습니다.
```javascript
//회원가입
router.post('/users', async (req, res) => {
  //로그인 중이면 에러 메세지
  const checkToken = req.headers['token'];

  if (checkToken.length) {
    res.status(401).send({
      errorMessage: '로그인 중임',
    });
    return;
  }
...
```
강의 내용을 따라하면서 만들었던 결과물에서는 
```javascript
if (localStorage.getItem('token')) {
        getSelf(function () {
          alert('이미 로그인이 되어있습니다. 상품 페이지로 이동합니다.');
          window.location.replace('/goods.html');
        });
      }
```
이런식으로 로그인을 할떄 `localStorage`라는 곳에 토큰을 저장하여 프론트 쪽에서 '로그인 중' 이라고 표현하는데 어떤 방식이 맞는 건지 궁금합니다

4. 이번에 주특기 주차를 진행하면서 `javascript` 문법이라고는 if문을 사용한 것이 전부인것 같은데 전체적으로 보시기에 줄일 수 있는 부분은 있는지 합치거나 분리 시켜야 하는 부분이 있는지 전체적인 평도 궁급합니다.

5. jest를 이용하여 회원가입, 로그인 부분 test를 해보는 추가 과제가 있었는데 `mocking`하지 않고 실제 api 자체를 테스트 할 수 있는 방법을 알고 싶은데 찾아봐도 이해가 안되거나 적용이 안되는 부분이 있어 좋은 자료 있으면 링크 부탁드립니다.

**Comment by ohbin-kwon** [comment]
이미 올려주신 질문들이 있어, 올려주신 질문과 함께 과제 리뷰 드리겠습니다.
일단 저는 root에 있는 과제를 제출하신줄알고,  front도 템플릿엔진을 구현해주신부분도 보았고,  mongoose가 아닌 sequalize를 이용해 구현해주신것도 보았습니다. 굉장히 정석적인 코드들을 잘 적어주셔서, 거의 틀린부분이 없는 코드들이라 매우 놀랐습니다.

질문에 대한 대답
1. path parameter를 여러개 사용할 수 있습니다. 예를 들어 /organizations/{orgId}/members/{memberId} 처럼 서버에서 두가지 parameter가 필요하면 사용할수 있겠지요. 그런데 영성님이 적어주신것처럼 '/posts/:postsId/:commentsId'라고 적으면 결국 '/post/123/233'으로 표기 되기 때문에 뒤의 233이 어떤것에 해당하는 id인지 알수가 없기때문에 '/posts/:postsId/comments/:commentsId' 라고 표기해야 합니다.
2. 지금 적어주신 method나 url은 restful하게 잘작성되었다고 생각합니다. root에 존재하는과제는 put에서 patch로 변경하셨던데, patch의 개념도 잘이해하시고 있는것같습니다. 저의 경우에는 회원가입할때 POST /new 이런식으로 작성했었는데 rest에도 이해가 꽤 깊으신것같습니다.
3. 로그인이 되어있는지 아닌지는 1차적으로 프론트코드에서 검증해주는게 맞습니다. 토큰을 가지고있는지 아닌지는 프론트가 알고있는것이니까요. 프론트엔드는 프론트엔드로써의 역할이 있고 백엔드는 백엔드로서의 역할이있습니다. 과거 프로그래밍과 달리 현대에는 프론트와 백엔드의 역할이 확실히 나누어져있고, 토큰을 관리하는것은 프론트엔드의 일이라고 생각하시면 좋을것같습니다. 백엔드는 단순히 인증이 필요한 요청에만 토큰검증을 하면됩니다(authmiddleware). authmiddleware라는것을 서버에서 만든것은 토큰이 있는지 없는지를 검증하기 위함이니 저렇게 실제 로직에서 header의 토큰을 검증할 필요가 없습니다. 애초에 회원가입은 '인증'과정이 필요없는 요청입니다. 프론트가 토큰을 localstorage에 가지고 있는지 아닌지는 서버가 검사할 영역이 아닙니다. 이부분 이해가 어려우시다면 게더순회때 이야기한번 더해봐요
4. 현재 모든 error에 대해 error response를 반환해주고 있는데, express의 errorhandling middleware를 참고하고 사용해보시면 좋을것같습니다. (https://expressjs.com/en/guide/error-handling.html) next(error)로 error를 넘긴다면, errorhandling middleware가 해당 에러를 일괄 처리해 줄 수 있습니다. 현재 프로젝트에는  다른 javascript문법을 적용할 만한 내용이 없어서 그렇습니다. if 말고 다른 conditional 구문을 써보고싶다면 좋을 레퍼런스 드리겠습니다(https://www.digitalocean.com/community/posts/5-tips-to-write-better-conditionals-in-javascript), id에대한 부분은 밑에 질문 드렸습니다.
5. test는 unittest와 e2etest가 있습니다. 현재 unitTest에 대해 물어보시는것같아 답해드립니다. test는 추상화된 함수 또는 class를 test하는것입니다. 현재 express코드는 테스트할 준비가 안된 코드입니다. 예를 들어서
`
router.post('/posts/:postsId', authMiddleware, async (req, res) => {
  const { nickname } = res.locals.user;
  const { comments } = req.body;
  const { postsId } = req.params;

  const maxCommentsId = await Comments.findOne().sort('-commentsId').exec();
  let commentsId = 1;

  if (maxCommentsId) {
    commentsId = maxCommentsId.commentsId + 1;
  }

  const createdComments = await Comments.create({ postsId, commentsId, nickname, comments });

  res.json({ comments: createdComments });
});
`
라는 코드가 있으면 저희는 여기서 테스트를 해야할부분이 req, res로 받아오는 부분을 제외한 부분을 테스트를 합니다. 객체지향적인 관점에서 req, res는 단지 요청을 주고 받는것이고, 안의 로직을 테스트해야함을 아시면 좋을것같습니다. 그렇다면
`
`
router.post('/posts/:postsId', authMiddleware, async (req, res) => {
  const { nickname } = res.locals.user;
  const { comments } = req.body;
  const { postsId } = req.params;

addComments()

  res.json({ comments: createdComments });
});

function addComment(){
  const maxCommentsId = await Comments.findOne().sort('-commentsId').exec();
  let commentsId = 1;

  if (maxCommentsId) {
    commentsId = maxCommentsId.commentsId + 1;
  }

  const createdComments = await Comments.create({ postsId, commentsId, nickname, comments });
}
`
와 같이 테스트해야합니다. 그런데 여기서도 문제점은 addComment라는 함수안에는 findOne, create이라는 mongoose에 의존한 코드를 가지고 있습니다. 결국 저희는 addComment라는 함수를 테스트 하기위해선 testCode에 mongoose의 findOne이라는 것을 require해서 사용해야합니다.
테스트코드는 그래서 의존성을 가지고 있는 코드에 대해 테스트를 하기가 쉽지않습니다. Joi부분을 다르게 생긴 코드로 바꿔서 테스트를 한것도 같은 이유입니다. Joi라는 의존성을 테스트하는것은 의미도 없고, Joi라는 의존성을 가진 코드를 테스트하려면 결국 Joi를 require해서 테스트해야하기 때문입니다.
결국 테스트라는것은 의존성을 제외한 코드로 추상화 -> 추상화한것을 테스트한다 라는 가정이 있어야하죠. 지금 구현한 코드를 테스트하는것은 api를 추상화해야합니다.
지금 코드를 가지고 테스트하는것보다, 앞으로 코드를 쓸때, 어떻게 코드를 추상화하고 어떤 부분을 테스트를 해야할지를 생각하는게 좋을것같아요
https://www.testim.io/blog/node-js-unit-testing-get-started-quickly-with-examples/
해당 글을 읽어보고 calculate.js를 어떻게 테스트하는지 보면 좋을것같습니다. 

궁금한점 및 더 공부하면 좋을점
1. 자동생성되는 id를 사용하지 않고 +1을 해서 새로운 id를 만들어준 이유가 있는지 궁금합니다.
2. 앞으로 mongoose를 사용하신다면 populate를 사용하셔서, ref하고 있는 schema의 정보들을 가져오는 방법도 익히시면 좋을것같습니다.(https://www.zerocho.com/category/MongoDB/post/59a66f8372262500184b5363)

**Comment by ohbin-kwon** [comment]
e2e test에 대한 내용이 빠졌는데, e2etest를 하고싶으시다면 supertest라는 패키지를 사용하는 것을 추천드립니다.
(https://inpa.tistory.com/591)

**Comment by lilclown97** [comment]
좋은 답변 감사합니다!!!!!!! 궁금했던 부분이 전부 해소 되어서 마음이 너무 가뿐합니다 핳
